---
- name: Install Docker on host1 machine
  hosts: host1
  become: true
  tasks:
    - name: Install Docker prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg2
          - software-properties-common
        state: present
      when: ansible_os_family == 'Debian'

    - name: Add Docker GPG Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: ansible_os_family == 'Debian'

    - name: Add Docker Repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present
      when: ansible_os_family == 'Debian'

    - name: Install Docker Engine
      apt:
        name: docker-ce
        state: present
      when: ansible_os_family == 'Debian'
